### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by kyre6371** [cecilialau6776/ldap_allocs#1]
I've followed the documentation here and the documentation at https://coldfront.readthedocs.io/en/latest/plugin/how_to_create_a_plugin/

I've tried the pip install approach as well as editing source code from coldfront to try and pull the plugin in. 
Django is unaware of any available migrations.

**Comment by cecilialau6776** [comment]
Migrations? My project doesn't deal with those, and you shouldn't need to edit any ColdFront source code. Did you get ColdFront working without this plugin?

**Comment by kyre6371** [comment]
Yes, I have Coldfront running. I have it setup with an ldap server, database, and cluster. I can create allocations and I have automated exporting of coldfront and slurm is ingesting these accounts. 

For migrations, I was just confused because after adding the plugin it didn't seem like anything changed. 

At first, I was getting error messages about the ldap_allocs plugin from local_settings.py. I'm not getting any error messages like I was initially. Coldfront starts now without any issues and ldap_allocs is installed. Its in the site-packages. I've edited my local_settings.py to include the plugin as directed. 

Are there logs or anything I can check that the ldap allocations are at least being attempted?

UPDATE: I see now that signals in coldfront.core.allocations are dispatching and that the functionality is completely tied to the receiving signals based on allocations (which is pretty much stated the first line of your readme file). I apologize for not looking into this in greater detail before commenting. A small bit about workflow or how to debug/test/logs might be useful in the readme. I will take notes while testing and see if there is any useful contribution.

**Comment by kyre6371** [comment]
I could put in a pull request for the README with some of the notes from this discussion if applicable.

**Comment by cecilialau6776** [comment]
> I could put in a pull request...
That'd be great, thank you so much!

> I apologize for not looking into this in greater detail...
No worries, sorry for not responding in greater detail earlier. I last worked on this quite a while ago and honestly don't remember the details.
